### ISSUE TITLE
Grav and wordpress; how do they work together.

### ISSUE THREAD

**Issue by crowesn** [SeattleDSA/dsa_wordpress#1]
Looks like you have some kind of integration between grav and wordpress? Would love to pick your brain about how this works. I'm working with some folks to set up a site for Cincinnati DSA Chapter.
I'm @crowesn on twitter if you're free and inclined.

**Comment by davidagnome** [comment]
We share some assets between the two and some functionality but that's about it. They can be used independently of one another
