### ISSUE TITLE
Are any additional plugins required to make this look like the official seattle dsa website?

### ISSUE THREAD

**Issue by jcklpe** [SeattleDSA/dsa_wordpress#4]
Hey, I'm helping the Austin branch redo their website and wanted to check in and see if I was missing any plugins to make it work.

**Comment by davidagnome** [comment]
The Homepage page template uses theeventscalendar plugin for pulling the event info. Aside from that, everything else should be included.

**Comment by jcklpe** [comment]
@davidagnome  If I can, have a couple other questions. I'll update these questions as individual comments as I work through this process. I'm actively exploring this process, and I'm finding answers but also more questions as I go along so please excuse the freeform nature of my documentation here

**Comment by jcklpe** [comment]
I see that stuff like the "read full platform" button is hardcoded to a specific page on the Seattle DSA website. So is that page a statically coded paged or is that generated using the theme?

**Comment by jcklpe** [comment]
I see the read full platform section, but I don't see where these other two sections are coming from:

![image](https://user-images.githubusercontent.com/9451726/63405120-51295d00-c3ab-11e9-8231-a3b3c9ec1baa.png)
versus what I'm getting:

![image](https://user-images.githubusercontent.com/9451726/63405187-8afa6380-c3ab-11e9-8f38-bc7d7e2720e1.png)

**Comment by jcklpe** [comment]
Hitting some errors too:
![image](https://user-images.githubusercontent.com/9451726/63405439-74a0d780-c3ac-11e9-8c11-0eef4d11b5eb.png)
Also trying to chase these errors down myself but not totally sure what's causing these issues.

**Comment by jcklpe** [comment]
Okay fixed some of those past errors. Looks like ACF does need to be installed: 
![image](https://user-images.githubusercontent.com/9451726/63405756-7c14b080-c3ad-11e9-8e26-2d3261a79574.png)

**Comment by jcklpe** [comment]
Well not sure how to fix those other errors. 

Also I see where to add stuff to the top menu and the footer links but not sure how the media for the footer links (like the icon of the state etc) are added.

**Comment by davidagnome** [comment]
2019 page template isn't ready for production. 

template-homepage-2017.php should still be in the repo and be the one you want.

Have you created a menu and assigned it to the Main Menu slot?

Fyi- there's an entire boilerplate DSA chapter theme without our chapter-specific artwork/bloat: 
https://github.com/SeattleDSA/dsa_wordpress_generic

**Comment by jcklpe** [comment]
@davidagnome  

Oh dope thanks. I'll try the generic version instead. 

EDIT: Just tried the generic version. The styling is so greatly reduced that I think I'm best off just taking what you guys have done and editing  in our changes from there. I'll continue building of the Seattle  theme, and I'll replace the hard-coded pieces of branding and as much of the copy pasted html etc stuff with ACF global fields as I can. You're welcome to pull our changes as I complete it if you guys think you will find it useful. I'm trying to get a theme under my belt that's easy for non-tech people to update because I want to help a couple of different non-profits here in town besides DSA, and a lot of these non-profits have almost zero tech talent so even something as simple as updating some copy pasted html is asking a lot. 

also thanks yeah I had the main menu working previously but just now checked the actual code and I can see how the bottom menu is built from sidebar widgets. Easy peasy!

Other than the event submissions page I'm not encountering anymore errors issues though. I'll close this issue as solved. Thanks! Solidarity.
