### ISSUE TITLE
Quick question about "_dsa_column_right"

### ISSUE THREAD

**Issue by jcklpe** [SeattleDSA/dsa_wordpress#5]
I've been working on the Austin fork of the theme here: https://github.com/jcklpe/nonprofit-wordpress

Been making a lot of changes in how stuff is organized according to my taste and some goals that I have going forward with what I'm planning on adding to the theme. (largely based on plans to further leverage gutenberg editor to do away with the need for page templates as much as possible). 

I had a quick question. 

I'm looking at how some of the custom fields are set up. I learned how to use WP in the context of ACF. So I've never actually learned the "native wordpress" way to set up custom fields. 

I think I get the gist but I just want to check in. 

Below is the relevant code I think and I've added my comments as `**//-**`

```
/* Adds a box to the main column on the Post and Page edit screens */

**//- So basically you write a function to that adds metaboxes to posts. You set the conditions based on templates.** 

**//- I don't get where the metabox _8 and metabox_11 comes up. What's that refer to? Are those just custom names? Why those specific numbers?** 


function myplugin_add_custom_box() {
  global $post;
    if ( 'template-homepage-2017.php' == get_post_meta( $post->ID, '_wp_page_template', true ) ) {
          add_meta_box( 'wp_editor_test_8_box', 'DSA Feature Box', 'wp_editor_meta_box_8' );
          add_meta_box( 'wp_editor_test_4_box', 'Final Row', 'wp_editor_meta_box_4' );
          add_meta_box( 'wp_editor_test_11_box', 'DSA Alert Box', 'wp_editor_meta_box_11' );
    }
    elseif ( 'template-homepage-2019.php' == get_post_meta( $post->ID, '_wp_page_template', true ) ) {
          add_meta_box( 'wp_editor_test_8_box', 'DSA Feature Box', 'wp_editor_meta_box_8' );
          add_meta_box( 'wp_editor_test_4_box', 'Final Row', 'wp_editor_meta_box_4' );
          add_meta_box( 'wp_editor_test_11_box', 'DSA Alert Box', 'wp_editor_meta_box_11' );
    }
}

**//- What's this stuff do? I can't even get an idea just from looking at it.** 
/* Prints the box content */
function wp_editor_meta_box_4( $post ) {

  // Use nonce for verification
  wp_nonce_field( plugin_basename( __FILE__ ), 'myplugin_noncename' );

  $field_value = get_post_meta( $post->ID, '_dsa_column_right', false );
  wp_editor( $field_value[0], '_dsa_column_right' );
}
```

and
```
//- Okay so for this it's basically saying "if there's crap in this post id's metabox metadata then post it here, right?
  if ( isset ( $_POST['_dsa_column_right'] ) ) {
    update_post_meta( $post_id, '_dsa_column_right', $_POST['_dsa_column_right'] );
  }
```

**Comment by davidagnome** [comment]
Sorry for the naming. There used to be a plague of metaboxes for providing additionally areas in the presentation of Homepage 2017.

The names used to be semantic. Working on cleaning up the code the past couple days. Basically those box #s can be renamed and repurposed to be associate with a page template's values. You can see how they're call in the page template file.

Box 8 on Homepage 2017 is used for the email subscribe feature on our homepage. Whereas the regular pageeditor does the big about us / call to action.

Box 11 stores the content for the DSA Alert Box. It displays on the 2017 homepage template as a modal dialog that can be closed. We use it if a event moves locations or is cancelled.

Box 4 is used as a heading area for Dispatches. At one point we had more links to topics or getting involved. In my latest commit, I removed it.


All of the meta boxes can be reused and renamed, so you can Box 8 something else and assign it its own presentation area.

Gutenburg rendered a lot of this redundant as it's easier to get complex presentations.

The new commit I pushed this morning cleared a lot of dead code, removed a ton of foundation's bloat. I also added clearer descriptions [i.e. "DSA Feature Box" renamed "MailChimp signup (Paste embed code)" in the Homepage 2017 page template, which should make it easier on people. Hoping to bake in native featured images to 
let chapters replacee the default, Seattle-specific mural Eva designed.

**Comment by jcklpe** [comment]
@davidagnome Excellent, yeah I just saw your commits. I actually wish I'd seen this earlier because I have changed the structure of the project so much that it might be a pain for me to fold in your additions. I'm going to take a crack at it though. Thank you for continuing to support this!

I mostly changed the structure because I like using scss and so I broke the styles.css into a bunch more parts. 

I also broke out some of the template into php partials. The reason for doing this was 

1. Because I find it easier to follow the structure of templates when they're componentized. This is simply a personal preference of mine. 

2. To eventually prepare things for Gutenberg stuff 

You can see an example of how I put these php partials into their own section here: https://github.com/jcklpe/nonprofit-wordpress/tree/master/assets/src/scss/blocks

It's under the SCSS currently which is a bit weird but eventually I'll probably be breaking out everything contained under "blocks" into a separate Gutenberg blocks plugin. For now I'm just trying to keep things simple though and not break the previous template. 

I'm also currently in the process of trying to make stuff more chapter agnostic too. 

My main question in this thread though was primarily me just trying to make sure I understood how custom metaboxes were added to WP. I see what you're saying about the naming, and that does answer part of my question. I guess the other stuff I'm trying to ask is just super super basic. Like I've never added metaboxes before so I'm not sure what all the php functions I quoted does. Like what does it mean for something to "print box content"?

**Comment by jcklpe** [comment]
Just finished adding custom logo functionality to the header logo image 😄

**Comment by jcklpe** [comment]
@davidagnome So I looked through all the changes you made last week and I decided that I'm just going to refork your work and remake my changes to that fork again. 

I don't know how you want to handle forks etc: I personally am planning on expanding out on the theme considerably for the use of non-profits I help here in Austin, and not just DSA. 

I don't want my changes to make it difficult for me to fold future changes by you in your fork into my fork. 

I also think that I'm adding a lot of useful stuff that will ultimately help your fork and might be worth you folding back into your fork. Which will be hard to do if our forks diverge too greatly or whatever. 

Do you have any opinions on how I should handle this? Like I said, I'm really just a design technologist so I've only ever worked on code in a single person context and I'm not actually that well versed on how to properly merge and fork my work in a team setting. I'm trying to learn though!

And I don't want to be a hassle or burden to you. I know you're a volunteer like me and probably very busy, but it would be at least good to know your thoughts on how you think I should be handling this stuff and what my expectations should be for keeping my fork in line with your fork going forward.

**Comment by jcklpe** [comment]
@davidagnome I'm going to close this issue and open a separate one about keeping us in sync so that we can have a clearer more structured conversation. This has extended to far outside the scope of the original ticket.
