### ISSUE TITLE
Dependencies missing from README

### ISSUE THREAD

**Issue by AbleLincoln** [SeattleDSA/dsa_wordpress#8]
Hey, I'm from the Los Angeles DSA chapter. We're forking your theme for our new site redesign. It's a gorgeous theme! I just had some issues getting things setup. The site was completely busted at first, until I realized that [The Events Calendar](https://theeventscalendar.com/wordpress-events-calendar/) has to be installed for the theme to work. 

Would it be possible to include this information in the README for anyone who wants to fork this theme in the future? Also, if there are any other required dependencies/plugins, listing those would be fantastic!

Thanks 🌹

**Comment by AbleLincoln** [comment]
expanding on this further: the source of the issue is in the `wp_head` hook. The `community_add_css` action relies on the Event Calendar being installed (it just breaks if the plugin is not installed):
https://github.com/SeattleDSA/dsa_wordpress/blob/8157f8bbf507ed82e2f0c78f74a27c269a5ce9fa/functions.php#L43-L51

I guess another solution could be to change how this function works so that the dependency is not required.

**Comment by AbleLincoln** [comment]
I'm dumb. I just realized that this already is in the README......... 

Sorry, my bad. However, it mentions that the dependency is optional when this is not the case. See above: the theme breaks if the plugin is not included.

**Comment by davidagnome** [comment]
Thanks. I can make it conditionally applied, if the plugin is enabled, similar to the plugin check used in the /parts/content-events.php file.

It was a hotfix due to a bug in The Events Calendar, so it may not even be needed anymore.

Will test both tonight and push some changes that make the printable and email upcoming events pages chapter agnostic.

**Comment by davidagnome** [comment]
Just pushed an update. It adds it conditionally as well as bugfixes, more chapter agnostic theming,  and page template use cases.

If you've already forked it, try copying the functions file over.
